Insert into Countries (Code, Name) values ('AFG','Afghanistan');
Insert into Countries (Code, Name) values ('ARG','Argentina');
Insert into Countries (Code, Name) values ('ABW','Aruba');
Insert into Countries (Code, Name) values ('AUS','Australia');
Insert into Countries (Code, Name) values ('BHS','Bahamas');
Insert into Countries (Code, Name) values ('BEL','Belgium');
Insert into Countries (Code, Name) values ('BRA','Brazil');
Insert into Countries (Code, Name) values ('BGR','Bulgaria');
Insert into Countries (Code, Name) values ('KHM','Cambodia');
Insert into Countries (Code, Name) values ('CMR','Cameroon');
Insert into Countries (Code, Name) values ('CAN','Canada');
Insert into Countries (Code, Name) values ('CHL','Chile');
Insert into Countries (Code, Name) values ('CHN','China');
Insert into Countries (Code, Name) values ('COL','Colombia');
Insert into Countries (Code, Name) values ('CZE','Czech Republic');
Insert into Countries (Code, Name) values ('DNK','Denmark');
Insert into Countries (Code, Name) values ('DOM','Dominican Republic');
Insert into Countries (Code, Name) values ('EGY','Egypt');
Insert into Countries (Code, Name) values ('FIN','Finland');
Insert into Countries (Code, Name) values ('FRA','France');
Insert into Countries (Code, Name) values ('GEO','Georgia');
Insert into Countries (Code, Name) values ('DEU','Germany');
Insert into Countries (Code, Name) values ('GRC','Greece');
Insert into Countries (Code, Name) values ('HKG','Hong Kong');
Insert into Countries (Code, Name) values ('HUN','Hungary');
Insert into Countries (Code, Name) values ('ISL','Iceland');
Insert into Countries (Code, Name) values ('IND','India');
Insert into Countries (Code, Name) values ('IDN','Indonesia');
Insert into Countries (Code, Name) values ('IRN','Iran');
Insert into Countries (Code, Name) values ('IRL','Ireland');
Insert into Countries (Code, Name) values ('ISR','Israel');
Insert into Countries (Code, Name) values ('ITA','Italy');
Insert into Countries (Code, Name) values ('JPN','Japan');
Insert into Countries (Code, Name) values ('KEN','Kenya');
Insert into Countries (Code, Name) values ('KGZ','Kyrgyzstan');
Insert into Countries (Code, Name) values ('LBY','Libya');
Insert into Countries (Code, Name) values ('MEX','Mexico');
Insert into Countries (Code, Name) values ('NDL','Netherlands');
Insert into Countries (Code, Name) values ('NZL','New Zealand');
Insert into Countries (Code, Name) values ('NGA','Nigeria');
Insert into Countries (Code, Name) values ('NOR','Norway');
Insert into Countries (Code, Name) values ('PAK','Pakistan');
Insert into Countries (Code, Name) values ('PAN','Panama');
Insert into Countries (Code, Name) values ('PER','Peru');
Insert into Countries (Code, Name) values ('PHL','Philippines');
Insert into Countries (Code, Name) values ('POL','Poland');
Insert into Countries (Code, Name) values ('ROU','Romania');
Insert into Countries (Code, Name) values ('RUS','Russia');
Insert into Countries (Code, Name) values ('SVK','Slovakia');
Insert into Countries (Code, Name) values ('SVN','Slovenia');
Insert into Countries (Code, Name) values ('ZAF','South Africa');
Insert into Countries (Code, Name) values ('KOR','South Korea');
Insert into Countries (Code, Name) values ('ESP','Spain');
Insert into Countries (Code, Name) values ('SWE','Sweden');
Insert into Countries (Code, Name) values ('CHE','Switzerland');
Insert into Countries (Code, Name) values ('TWN','Taiwan');
Insert into Countries (Code, Name) values ('THA','Thailand');
Insert into Countries (Code, Name) values ('TUR','Turkey');
Insert into Countries (Code, Name) values ('GBR','UK');
Insert into Countries (Code, Name) values ('ARE','United Arab Emirates');
Insert into Countries (Code, Name) values ('USA','USA');